# Generated by Django 6.1.1 on 2026-09-04 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Наприклад: Іванов Іван Іванович', max_length=150, verbose_name='ПІБ працівника')),
                ('tax_id', models.CharField(help_text='Наприклад: 3126501237', max_length=10, verbose_name='РНОКПП (ІПН)')),
                ('birth_date', models.DateField(verbose_name='Дата народження')),
                ('position', models.CharField(help_text='Згідно з класифікатором професій', max_length=150, verbose_name='Посада')),
                ('hire_date', models.DateField(verbose_name='Дата прийняття на роботу')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оклад (грн)')),
                ('is_primary', models.BooleanField(default=True, help_text='Якщо Ні — сумісництво (неосновне)', verbose_name='Основне місце роботи')),
                ('tax_privilege', models.CharField(choices=[('none', 'Без пільги'), ('100', '100% НСП (базова)'), ('150', '150% НСП (одинова мати / діти-інваліди)'), ('200', '200% НСП')], default='none', max_length=10, verbose_name='Пільга з ПДФО')),
                ('work_schedule', models.CharField(choices=[('full_40', "П'ятиденка (40год/тиж, 8 год/день"), ('part_20', 'Неповний робочий день (20 год/тиж, 4 год/день)'), ('part_10', 'Неповний робочий день (10 год/тиж, 2 год/день)'), ('shift', 'Змінний графік')], default='full_40', max_length=20, verbose_name='Графік роботи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Працює')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено в системі')),
                ('fop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='fops.fops', verbose_name='ФОП Роботодавець')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
                'ordering': ['full_name'],
            },
        ),
    ]
