# Generated by Django 6.1.1 on 2026-09-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('main', 'Основне місце'), ('part_time', 'Сумісництво')], default='main', max_length=20),
        ),
    ]
