# Generated by Django 6.1.1 on 2026-09-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_employment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('hire', 'Наказ про прийняття на роботу'), ('dismissal_agreement', 'Наказ про звільнення за згодою сторін')], max_length=30, verbose_name='Тип наказу')),
                ('order_num', models.CharField(max_length=50, verbose_name='Номер наказу')),
                ('order_date', models.DateField(verbose_name='Дата наказу')),
                ('effective_date', models.DateField(verbose_name='Дата дії (початку/звільнення)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='employees.employee', verbose_name='Працівник')),
            ],
        ),
    ]
