# Generated by Django 6.1.1 on 2026-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='insured_category',
            field=models.CharField(choices=[('1', '1 - Наймані працівники з трудовою книжкою (основне місце)'), ('2', '2 - Наймані працівники без трудовою книжки (сумісництво)'), ('3', '3 - Гіг-фахівці (за гіг-контрактом)')], default='1', max_length=2, verbose_name='Категорія застрахованої особи'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_ukrainian_citizen',
            field=models.BooleanField(default=True, verbose_name='Громадянин України (1 - Так, 0 - Ні)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_info',
            field=models.CharField(blank=True, help_text='Серія та номер або номер ID-картки', max_length=50, null=True, verbose_name='Паспортні дані'),
        ),
    ]
