# Generated by Django 6.1.1 on 2026-09-04 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_employment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Місяць')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Рік')),
                ('norm_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Норма годин')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Відпрацьовано годин')),
                ('status', models.CharField(choices=[('draft', 'Черновий'), ('approved', 'Затверджений')], default='draft', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='employees.employee', verbose_name='Працівник')),
            ],
            options={
                'verbose_name': 'Табель',
                'verbose_name_plural': 'Табелі',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TimesheetDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('day_type', models.CharField(choices=[('WORK', 'Робочий'), ('WEEKEND', 'Вихідний'), ('VACATION', 'Відпустка'), ('SICK', 'Лікарняний')], default='WORK', max_length=10, verbose_name='Тип дня')),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Години')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='timesheet.timesheet', verbose_name='Табель')),
            ],
            options={
                'verbose_name': 'День табеля',
                'verbose_name_plural': 'Дні табеля',
                'ordering': ['date'],
                'unique_together': {('timesheet', 'date')},
            },
        ),
    ]
