# Generated by Django 6.1.1 on 2026-09-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Наприклад: Іванов Іван Іванович', max_length=255, verbose_name='ПІБ ФОП')),
                ('tax_id', models.CharField(help_text='Наприклад: 3126501237', max_length=10, unique=True, verbose_name='РНОКПП (ІПН)')),
                ('address', models.TextField(verbose_name='Податкова адреса (по прописці)')),
                ('tax_system', models.CharField(choices=[('group_1', 'Єдиний податок - 1 група'), ('group_2', 'Єдиний податок - 2 група'), ('group_3_5', 'Єдиний податок - 3 група (5%)'), ('group_3_pdv', 'Єдиний податок - 3 група (3% + ПДВ)'), ('general', 'Загальна система оподаткування')], default='group_2', help_text='Наприклад: group_2', max_length=20, verbose_name='Система оподаткування')),
                ('iban', models.CharField(blank=True, help_text='Наприклад: UA853996220000000260012335661', max_length=35, null=True, verbose_name='Розрахунковий рахунок (IBAN)')),
                ('kved', models.CharField(blank=True, help_text="Наприклад: 62.01 Комп'ютерне програмування", max_length=255, null=True, verbose_name='Основний КВЕД')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'ФОП',
                'verbose_name_plural': 'ФОПи',
                'ordering': ['full_name'],
            },
        ),
    ]
