# Generated by Django 6.1.1 on 2026-09-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fops',
            options={'verbose_name': 'ФОП', 'verbose_name_plural': 'ФОПи'},
        ),
        migrations.RemoveField(
            model_name='fops',
            name='address',
        ),
        migrations.RemoveField(
            model_name='fops',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='fops',
            name='kved',
        ),
        migrations.AddField(
            model_name='fops',
            name='additional_kveds',
            field=models.TextField(blank=True, verbose_name='Перелік додаткових КВЕДів'),
        ),
        migrations.AddField(
            model_name='fops',
            name='building',
            field=models.CharField(blank=True, max_length=50, verbose_name='Будинок / Квартира'),
        ),
        migrations.AddField(
            model_name='fops',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Населений пункт'),
        ),
        migrations.AddField(
            model_name='fops',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='fops',
            name='dps_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Код ДПС'),
        ),
        migrations.AddField(
            model_name='fops',
            name='dps_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва ДПС'),
        ),
        migrations.AddField(
            model_name='fops',
            name='katottg',
            field=models.CharField(blank=True, max_length=19, verbose_name='Код КАТОТТГ'),
        ),
        migrations.AddField(
            model_name='fops',
            name='main_kved',
            field=models.CharField(blank=True, max_length=100, verbose_name='Основний КВЕД'),
        ),
        migrations.AddField(
            model_name='fops',
            name='opf_code',
            field=models.CharField(default='910', help_text='910 — Фізична особа - підприємець', max_length=10, verbose_name='Код ОПФ'),
        ),
        migrations.AddField(
            model_name='fops',
            name='pfu_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Код органу ПФУ'),
        ),
        migrations.AddField(
            model_name='fops',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='Поштовий індекс'),
        ),
        migrations.AddField(
            model_name='fops',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='fops',
            name='street',
            field=models.CharField(blank=True, max_length=150, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='fops',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fops',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fops',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ПІБ ФОП'),
        ),
        migrations.AlterField(
            model_name='fops',
            name='tax_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='Податковий номер (ІПН / ЄДРПОУ)'),
        ),
        migrations.AlterField(
            model_name='fops',
            name='tax_system',
            field=models.CharField(choices=[('EP_1', 'Спрощена (1 група)'), ('EP_2', 'Спрощена (2 група)'), ('EP_3_5', 'Спрощена (3 група 5%)'), ('EP_3_3', 'Спрощена (3 група 3% + ПДВ)'), ('GENERAL', 'Загальна система')], default='EP_3_5', max_length=20, verbose_name='Система оподаткування'),
        ),
    ]
