# Generated by Django 6.1.1 on 2026-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('EMPLOYMENT_NOTICE', 'Повідомлення про прийняття працівника'), ('UNIFIED_TAX_REPORT', 'Обєднаний звіт (ПДФО/ЄСВ)')], max_length=30, verbose_name='Тип звіту')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='Місяць')),
                ('period_year', models.PositiveIntegerField(verbose_name='Рік')),
                ('file', models.FileField(blank=True, null=True, upload_to='tax_reports_xml/', verbose_name='XML Файл')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновий'), ('GENERATED', 'Згенеровано XML'), ('SENT', 'Відправлено в ДПС')], default='DRAFT', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Податковий звіт',
                'verbose_name_plural': 'Податкові звіти',
            },
        ),
    ]
