# Generated by Django 6.1.1 on 2026-09-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='Номер заказу')),
                ('order_date', models.DateField(verbose_name='Дата наказу')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='orders/pdf/', verbose_name='PDF-file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_order', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Наказ про прийняття',
                'verbose_name_plural': 'Накази про прийняття',
            },
        ),
    ]
