# Generated by Django 6.1.1 on 2026-09-04 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оклад')),
                ('norm_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Норма годин')),
                ('worked_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Відпрацьовано годин')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нараховано (Gross)')),
                ('pdfo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ПДФО (18%)')),
                ('vz', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Військовий збір (5%)')),
                ('esv', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ЄСВ (22%)')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='До виплати (Net)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_calculation', to='timesheet.timesheet', verbose_name='Табель')),
            ],
            options={
                'verbose_name': 'Розрахунок зарплати',
                'verbose_name_plural': 'Розрахунки зарплати',
            },
        ),
    ]
