# Generated by Django 6.1.1 on 2026-09-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('sent', 'Відправлено'), ('accepted', 'Прийнято (Квитанція №2)')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='dps/xml/', verbose_name='XML file')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dps_notification', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Повідомлення ДПС',
                'verbose_name_plural': 'Повідомлення ДПС',
            },
        ),
    ]
